// Five hand-curated literary events at real coordinates.
// Schema mirrors what app/api/events/route.ts returns.
window.PARALLELS_EVENTS = [
  {
    id: "evt-rask",
    book: "Crime and Punishment",
    bookZh: "罪与罚",
    author: "Fyodor Dostoevsky",
    authorZh: "陀思妥耶夫斯基",
    character: "拉斯柯尔尼科夫",
    class: "知识分子",
    gender: "男",
    tags: "大学生",
    event: "在干草广场附近徘徊整整一夜，决定明日动手。",
    quote: "他在街上走来走去，仿佛一个置身梦中的人。",
    locationName: "圣彼得堡 · 干草广场",
    city: "St Petersburg",
    year: 1865,
    timeType: "历史锚定",
    locationType: "真实",
    lat: 59.927, lng: 30.319,
  },
  {
    id: "evt-scarlett",
    book: "Gone with the Wind",
    bookZh: "飘",
    author: "Margaret Mitchell",
    authorZh: "玛格丽特·米切尔",
    character: "Scarlett O'Hara",
    class: "贵族",
    gender: "女",
    tags: "庄园主",
    event: "亚特兰大失守，她带着妹妹与婴儿逃回塔拉。",
    quote: "毕竟，明天又是新的一天。",
    locationName: "亚特兰大",
    city: "Atlanta",
    year: 1864,
    timeType: "历史锚定",
    locationType: "真实",
    lat: 33.749, lng: -84.388,
  },
  {
    id: "evt-baoyu",
    book: "Dream of the Red Chamber",
    bookZh: "红楼梦",
    author: "Cao Xueqin",
    authorZh: "曹雪芹",
    character: "贾宝玉",
    class: "贵族",
    gender: "男",
    tags: "公子",
    event: "在大观园潇湘馆外读书，听见竹叶被雨打散的声音。",
    quote: "无故寻愁觅恨，有时似傻如狂。",
    locationName: "京城 · 大观园（虚构）",
    city: "Beijing",
    year: 1735,
    timeType: "虚构映射",
    locationType: "虚构映射",
    lat: 39.916, lng: 116.397,
  },
  {
    id: "evt-jval",
    book: "Les Misérables",
    bookZh: "悲惨世界",
    author: "Victor Hugo",
    authorZh: "雨果",
    character: "Jean Valjean",
    class: "底层",
    gender: "男",
    tags: "前苦役犯",
    event: "在迪涅主教家投宿，黎明前带走银烛台。",
    quote: "我把你的灵魂从黑暗中赎回来。",
    locationName: "迪涅",
    city: "Digne",
    year: 1815,
    timeType: "历史锚定",
    locationType: "真实",
    lat: 44.092, lng: 6.236,
  },
  {
    id: "evt-josefk",
    book: "The Trial",
    bookZh: "审判",
    author: "Franz Kafka",
    authorZh: "卡夫卡",
    character: "Josef K.",
    class: "资产阶级",
    gender: "男",
    tags: "银行职员",
    event: "三十岁生日清晨被两名看守逮捕，但谁也说不清罪名。",
    quote: "有人一定诬陷了约瑟夫·K，因为他没有做过什么坏事。",
    locationName: "布拉格（虚构映射）",
    city: "Prague",
    year: 1914,
    timeType: "创作年代",
    locationType: "虚构映射",
    lat: 50.087, lng: 14.421,
  },
];
